version: "3"
services:
  database:
    image: postgres:16.0-alpine
    env_file:
      - .dbcredentials.env
    volumes:
      - doniak_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: doniak-dataset-django
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .dbcredentials.env
    volumes:
      - django_media:/usr/app/media
      - django_static:/usr/app/staticfiles
    restart: always
    ports:
     - "127.0.0.1:8000:8000"
volumes:
  doniak_postgres_data:
  django_media:
  django_static: